version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pass_in_2
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    networks:
      - dev

networks:
  dev: